from telegram import Update
from telegram.ext import ContextTypes
from abc import ABC, abstractmethod

class BotCommandHandler(ABC):
  @abstractmethod
  async def start(self, update: Update, context: ContextTypes.DEFAULT_TYPE): ...
  @abstractmethod
  async def help(self, update: Update, context: ContextTypes.DEFAULT_TYPE): ...
  @abstractmethod
  async def get(self, update: Update, context: ContextTypes.DEFAULT_TYPE): ...
  @abstractmethod
  async def new(self, update: Update, context: ContextTypes.DEFAULT_TYPE): ...
  @abstractmethod
  async def update(self, update: Update, context: ContextTypes.DEFAULT_TYPE): ...
  @abstractmethod
  async def delete(self, update: Update, context: ContextTypes.DEFAULT_TYPE): ...
  @abstractmethod
  async def handler_inputs(self, update: Update, context: ContextTypes.DEFAULT_TYPE): ...
