from abc import ABC, abstractmethod
from src.shared import schemas

class CourseRepository(ABC):
  @abstractmethod
  def create_new_course(self, course: schemas.CourseIn): ...
  @abstractmethod
  def find_courses(self): ...
  @abstractmethod
  def find_course_by_id(self, id: int): ...
  @abstractmethod
  def update_course_by_id(self, id: int, course: dict): ...
  @abstractmethod
  def delete_course_by_id(self, id: int): ...