from abc import ABC, abstractmethod

class UserStateManager(ABC):
    @abstractmethod
    def get(self, user_id): ...
    @abstractmethod
    def set(self, user_id, state: dict): ...
    @abstractmethod
    def delete(self, user_id): ...
    @abstractmethod
    def has(self, user_id): ...